/* Seed data — demo alumni and students pre-loaded on first run */
import { getUsers, setUsers, generateId } from './storage';

const SEED_ALUMNI = [
  {
    id: 'alumni_001',
    name: 'Priya Sharma',
    email: 'priya.sharma@alumni.edu',
    password: 'demo123',
    role: 'alumni',
    department: 'Computer Science',
    graduationYear: 2020,
    jobTitle: 'Senior Software Engineer',
    employer: 'Google India',
    industry: ['Software Development', 'Cloud Computing', 'AI & ML'],
    experience: 5,
    skills: ['Python', 'React', 'Machine Learning', 'System Design', 'Cloud Architecture'],
    areasToMentor: ['Software Development', 'Interview Preparation', 'Career Growth', 'Tech Industry'],
    maxMentees: 3,
    currentMentees: 0,
    meetingMode: 'Online',
    availability: ['Monday', 'Wednesday', 'Saturday'],
    mentorshipStyle: 'Structured',
    bio: 'Passionate about helping fresh graduates navigate the tech industry. I focus on practical coding skills and interview preparation.',
    linkedin: 'https://linkedin.com/in/priyasharma',
    verified: true,
    profileComplete: true,
    createdAt: '2026-01-15',
  },
  {
    id: 'alumni_002',
    name: 'Rahul Patel',
    email: 'rahul.patel@alumni.edu',
    password: 'demo123',
    role: 'alumni',
    department: 'Information Technology',
    graduationYear: 2018,
    jobTitle: 'Product Manager',
    employer: 'Microsoft',
    industry: ['Product Management', 'Software Development', 'Cloud Computing'],
    experience: 7,
    skills: ['Product Strategy', 'Agile', 'Data Analytics', 'SQL', 'User Research'],
    areasToMentor: ['Product Management', 'Career Transition', 'Leadership', 'Tech Industry'],
    maxMentees: 2,
    currentMentees: 0,
    meetingMode: 'Both',
    availability: ['Tuesday', 'Thursday', 'Sunday'],
    mentorshipStyle: 'Casual',
    bio: 'Transitioned from engineering to product management. Happy to guide students exploring non-traditional tech careers.',
    linkedin: 'https://linkedin.com/in/rahulpatel',
    verified: true,
    profileComplete: true,
    createdAt: '2026-01-20',
  },
  {
    id: 'alumni_003',
    name: 'Ananya Desai',
    email: 'ananya.desai@alumni.edu',
    password: 'demo123',
    role: 'alumni',
    department: 'Data Science',
    graduationYear: 2021,
    jobTitle: 'Data Scientist',
    employer: 'Amazon',
    industry: ['Data Science', 'AI & ML', 'E-Commerce'],
    experience: 4,
    skills: ['Python', 'TensorFlow', 'Statistics', 'SQL', 'NLP', 'Deep Learning'],
    areasToMentor: ['Data Science', 'Machine Learning', 'Research', 'Interview Preparation'],
    maxMentees: 3,
    currentMentees: 1,
    meetingMode: 'Online',
    availability: ['Monday', 'Friday', 'Saturday'],
    mentorshipStyle: 'Structured',
    bio: 'Research-driven data scientist. I help mentees build strong ML portfolios and prepare for data science roles.',
    linkedin: 'https://linkedin.com/in/ananyadesai',
    verified: true,
    profileComplete: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'alumni_004',
    name: 'Vikram Singh',
    email: 'vikram.singh@alumni.edu',
    password: 'demo123',
    role: 'alumni',
    department: 'Mechanical Engineering',
    graduationYear: 2019,
    jobTitle: 'Operations Manager',
    employer: 'Tata Motors',
    industry: ['Manufacturing', 'Automotive', 'Operations'],
    experience: 6,
    skills: ['Supply Chain', 'Lean Manufacturing', 'AutoCAD', 'Project Management', 'Six Sigma'],
    areasToMentor: ['Manufacturing', 'Operations', 'Career Growth', 'Core Engineering'],
    maxMentees: 2,
    currentMentees: 0,
    meetingMode: 'Both',
    availability: ['Wednesday', 'Saturday', 'Sunday'],
    mentorshipStyle: 'Goal-Oriented',
    bio: 'Helping mechanical engineering students bridge the gap between academics and industry. Core engineering is alive and thriving!',
    linkedin: 'https://linkedin.com/in/vikramsingh',
    verified: true,
    profileComplete: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'alumni_005',
    name: 'Sneha Kulkarni',
    email: 'sneha.kulkarni@alumni.edu',
    password: 'demo123',
    role: 'alumni',
    department: 'Business Administration',
    graduationYear: 2017,
    jobTitle: 'Marketing Director',
    employer: 'Flipkart',
    industry: ['Marketing', 'E-Commerce', 'Digital Marketing'],
    experience: 8,
    skills: ['Digital Marketing', 'Brand Strategy', 'Analytics', 'Content Marketing', 'SEO'],
    areasToMentor: ['Marketing', 'Entrepreneurship', 'Career Growth', 'Leadership'],
    maxMentees: 3,
    currentMentees: 0,
    meetingMode: 'Online',
    availability: ['Tuesday', 'Thursday', 'Saturday'],
    mentorshipStyle: 'Casual',
    bio: 'From MBA to marketing leadership — I love helping students discover their strengths and build personal brands.',
    linkedin: 'https://linkedin.com/in/snehakulkarni',
    verified: true,
    profileComplete: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'alumni_006',
    name: 'Arjun Mehta',
    email: 'arjun.mehta@alumni.edu',
    password: 'demo123',
    role: 'alumni',
    department: 'Computer Science',
    graduationYear: 2022,
    jobTitle: 'Full Stack Developer',
    employer: 'Razorpay',
    industry: ['Software Development', 'FinTech', 'Startups'],
    experience: 3,
    skills: ['JavaScript', 'React', 'Node.js', 'MongoDB', 'Docker', 'TypeScript'],
    areasToMentor: ['Software Development', 'Startups', 'Interview Preparation', 'Web Development'],
    maxMentees: 4,
    currentMentees: 1,
    meetingMode: 'Online',
    availability: ['Monday', 'Wednesday', 'Friday'],
    mentorshipStyle: 'Structured',
    bio: 'Recent grad turned full-stack dev at a top fintech. I know what it takes to crack startup interviews fresh out of college.',
    linkedin: 'https://linkedin.com/in/arjunmehta',
    verified: true,
    profileComplete: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'alumni_007',
    name: 'Kavita Nair',
    email: 'kavita.nair@alumni.edu',
    password: 'demo123',
    role: 'alumni',
    department: 'Electronics',
    graduationYear: 2016,
    jobTitle: 'Embedded Systems Architect',
    employer: 'Qualcomm',
    industry: ['Semiconductors', 'Embedded Systems', 'IoT'],
    experience: 9,
    skills: ['C/C++', 'RTOS', 'VHDL', 'PCB Design', 'IoT', 'ARM Architecture'],
    areasToMentor: ['Embedded Systems', 'Core Engineering', 'Research', 'Higher Education'],
    maxMentees: 2,
    currentMentees: 0,
    meetingMode: 'Both',
    availability: ['Tuesday', 'Saturday'],
    mentorshipStyle: 'Goal-Oriented',
    bio: 'Decade in embedded systems. I guide students into the fascinating world of hardware-software co-design.',
    linkedin: 'https://linkedin.com/in/kavitanair',
    verified: true,
    profileComplete: true,
    createdAt: '2026-03-05',
  },
  {
    id: 'alumni_008',
    name: 'Rohan Joshi',
    email: 'rohan.joshi@alumni.edu',
    password: 'demo123',
    role: 'alumni',
    department: 'Finance',
    graduationYear: 2019,
    jobTitle: 'Investment Analyst',
    employer: 'Goldman Sachs',
    industry: ['Finance', 'Investment Banking', 'FinTech'],
    experience: 6,
    skills: ['Financial Modeling', 'Valuation', 'Excel', 'Python', 'Bloomberg Terminal'],
    areasToMentor: ['Finance', 'Investment Banking', 'Interview Preparation', 'Career Growth'],
    maxMentees: 2,
    currentMentees: 0,
    meetingMode: 'Online',
    availability: ['Sunday', 'Wednesday'],
    mentorshipStyle: 'Structured',
    bio: 'Finance professional who cracked the investment banking path. Let me help you navigate the world of high finance.',
    linkedin: 'https://linkedin.com/in/rohanjoshi',
    verified: true,
    profileComplete: true,
    createdAt: '2026-03-10',
  },
];

const SEED_ADMIN = {
  id: 'admin_001',
  name: 'Dr. Meera Iyer',
  email: 'admin@college.edu',
  password: 'admin123',
  role: 'admin',
  department: 'Administration',
  profileComplete: true,
  createdAt: '2026-01-01',
};

export function seedDataIfNeeded() {
  const users = getUsers();
  if (users.length === 0) {
    const allUsers = [...SEED_ALUMNI, SEED_ADMIN];
    setUsers(allUsers);
    return true;
  }
  return false;
}
